name: PHP Linting

on: [push]

jobs:
  php-linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Lint PHP files using PHP-CS-Fixer
      run: vendor/bin/php-cs-fixer fix --verbose --dry-run --diff
